jobs:
  - <<: (( merge ))
  - name: fetch-containers-images
    templates:
      - name: docker_load_images
        release: docker-broker-images
    instances: 1
    resource_pool: default
    lifecycle: errand
    networks:
      - name: default
        default: [dns, gateway]

properties:
  docker:
    tcp_address: 0.0.0.0

  broker:
    fetch_images: false # use `bosh run errand fetch-containers-images` so broker is not blocked


  docker_broker_images:
    docker_nodes: (( jobs.docker.networks.default.static_ips ))

